// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "dc4f3882-6712-4b7c-839a-9b2cd5cbabbe";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onDayIntensityChange();
void onOnSchedulerChange();

CloudPercentage day_intensity;
CloudRelativeHumidity moist_4;
CloudSchedule onScheduler;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(day_intensity, READWRITE, ON_CHANGE, onDayIntensityChange);
  ArduinoCloud.addProperty(moist_4, READ, 60 * SECONDS, NULL);
  ArduinoCloud.addProperty(onScheduler, READWRITE, ON_CHANGE, onOnSchedulerChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
